lib/sloth_web/router.ex
defmodule SlothWeb.Router do
  use SlothWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    #this assigns the current_user to conn
    plug Doorman.Login.Session
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :restricted do
    plug SlothWeb.RequireLogin
  end

  scope "/", SlothWeb do
    pipe_through :browser # Use the default browser stack

    resources "/notes", NoteController
    resources "/messages", MessageController
    resources "/posts", PostController
    resources "/clicks", ClickController
    resources "/users", UserController
    resources "/sessions", SessionController
    resources "/boards", BoardController
    get "/login", SessionController, :new
    get "/sign_up", UserController, :new
  end

  scope "/", SlothWeb do
    pipe_through :browser # Use the default browser stack
    pipe_through :restricted

    get "/", PageController, :index
    get "/home", PageController, :home

    get "/reddit", BoomController, :home
  end

  # Other scopes may use custom stacks.
  # scope "/api", SlothWeb do
  #   pipe_through :api
  # end
end

lib/sloth/booms/post.ex
defmodule Sloth.Booms.Post do
  use Ecto.Schema
  import Ecto.Changeset
  alias Sloth.Booms.Post


  schema "posts" do
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(%Post{} = post, attrs) do
    post
    |> cast(attrs, [:title])
    |> validate_required([:title])
  end
end

lib/sloth_web/controllers/post_controller.ex
defmodule SlothWeb.PostController do
  use SlothWeb, :controller
  alias Sloth.Booms.Post
  alias Sloth.Booms.Click
  alias Sloth.Booms

  import IEx

  def index(conn, _params) do
    user = conn.assigns[:current_user]
    changeset = Post.changeset(%Post{}, %{})

    clicks = Sloth.Repo.all(Click)
      |> Enum.map(fn x -> x.post_id end)
      |> Enum.group_by(fn x -> x end)

    posts = Sloth.Repo.all(Post)

    render(conn, "index.html", changeset: changeset, posts: posts, clicks: clicks)
  end

  def new(conn, _params) do
    changeset = Post.changeset(%Post{}, %{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    case Booms.create_post(post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: post_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
  end

  def edit(conn, %{"id" => id}) do
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
  end

  def delete(conn, %{"id" => id}) do
  end

end

lib/sloth_web/views/post_view.ex
defmodule SlothWeb.PostView do
  use SlothWeb, :view
end

lib/sloth_web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/sloth_web/templates/post/index.html.eex
<script>window.userToken = "<%= Phoenix.Token.sign(SlothWeb.Endpoint, "user salt", assigns[:current_user].id) %>"</script>

<h2>Add Post</h2>

<%= render "form.html", Map.put(assigns, :action, post_path(@conn, :create)) %>


<script type="text/javascript">
  function post_click(url, id) {
    global_channel.push("post_click", {'post_id': id}) 
    // window.open(url,'_blank');
  }

  var global_channel = null;
</script>



<%= for post <- @posts do %>
    <p id="post<%=post.id%>" ><%= post.title %> <span> clicks <%= length(@clicks[post.id] || []) %></span></p>
    <script type="text/javascript">
      document.getElementById("post<%=post.id%>").onclick = function() {
        post_click('<%=post.title%>', <%=post.id%>);
      }
    </script>
<% end %>



<script src="<%= static_path(@conn, "/js/post.js") %>"></script>

<%= render "three.html", assigns %>
<%= render "pointerlock.html", assigns %>

<script type="text/javascript">
        var camera, scene, renderer;
      var geometry, material, mesh;
      var controls;

      var objects = [];

      var raycaster;

      var blocker = document.getElementById( 'blocker' );
      var instructions = document.getElementById( 'instructions' );

      // http://www.html5rocks.com/en/tutorials/pointerlock/intro/

      var havePointerLock = 'pointerLockElement' in document || 'mozPointerLockElement' in document || 'webkitPointerLockElement' in document;

      if ( havePointerLock ) {

        var element = document.body;

        var pointerlockchange = function ( event ) {

          if ( document.pointerLockElement === element || document.mozPointerLockElement === element || document.webkitPointerLockElement === element ) {

            controlsEnabled = true;
            controls.enabled = true;

            // blocker.style.display = 'none';

          } else {

            controls.enabled = false;

            // blocker.style.display = '-webkit-box';
            // blocker.style.display = '-moz-box';
            // blocker.style.display = 'box';

            // instructions.style.display = '';

          }

        };

        var pointerlockerror = function ( event ) {

          // instructions.style.display = '';

        };

        // Hook pointer lock state change events
        document.addEventListener( 'pointerlockchange', pointerlockchange, false );
        document.addEventListener( 'mozpointerlockchange', pointerlockchange, false );
        document.addEventListener( 'webkitpointerlockchange', pointerlockchange, false );

        document.addEventListener( 'pointerlockerror', pointerlockerror, false );
        document.addEventListener( 'mozpointerlockerror', pointerlockerror, false );
        document.addEventListener( 'webkitpointerlockerror', pointerlockerror, false );


      } else {

        // instructions.innerHTML = 'Your browser doesn\'t seem to support Pointer Lock API';

      }

      init();
      animate();

      var controlsEnabled = false;

      var moveForward = false;
      var moveBackward = false;
      var moveLeft = false;
      var moveRight = false;
      var canJump = false;

      var prevTime = performance.now();
      var velocity = new THREE.Vector3();

      function init() {

        camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 1, 1000 );

        scene = new THREE.Scene();
        scene.background = new THREE.Color( 0xffffff );
        scene.fog = new THREE.Fog( 0xffffff, 0, 750 );

        var light = new THREE.HemisphereLight( 0xeeeeff, 0x777788, 0.75 );
        light.position.set( 0.5, 1, 0.75 );
        scene.add( light );

        controls = new THREE.PointerLockControls( camera );
        scene.add( controls.getObject() );

        var onKeyDown = function ( event ) {

          switch ( event.keyCode ) {

            case 38: // up
            case 87: // w
              moveForward = true;
              break;

            case 37: // left
            case 65: // a
              moveLeft = true; break;

            case 40: // down
            case 83: // s
              moveBackward = true;
              break;

            case 39: // right
            case 68: // d
              moveRight = true;
              break;

            case 32: // space
              velocity.y += 350;
              break;

          }

        };

        var onKeyUp = function ( event ) {

          switch( event.keyCode ) {

            case 38: // up
            case 87: // w
              moveForward = false;
              break;

            case 37: // left
            case 65: // a
              moveLeft = false;
              break;

            case 40: // down
            case 83: // s
              moveBackward = false;
              break;

            case 39: // right
            case 68: // d
              moveRight = false;
              break;
            case 32: // space
              velocity.y = 0;
              break;  

          }

        };

        document.addEventListener( 'keydown', onKeyDown, false );
        document.addEventListener( 'keyup', onKeyUp, false );

        // floor

        geometry = new THREE.PlaneGeometry( 2000, 2000, 100, 100 );
        geometry.rotateX( - Math.PI / 2 );

        for ( var i = 0, l = geometry.vertices.length; i < l; i ++ ) {

          var vertex = geometry.vertices[ i ];
          vertex.x += Math.random() * 20 - 10;
          vertex.y += Math.random() * 2;
          vertex.z += Math.random() * 20 - 10;

        }

        for ( var i = 0, l = geometry.faces.length; i < l; i ++ ) {

          var face = geometry.faces[ i ];
          face.vertexColors[ 0 ] = new THREE.Color().setHSL( Math.random() * 0.3 + 0.5, 0.75, Math.random() * 0.25 + 0.75 );
          face.vertexColors[ 1 ] = new THREE.Color().setHSL( Math.random() * 0.3 + 0.5, 0.75, Math.random() * 0.25 + 0.75 );
          face.vertexColors[ 2 ] = new THREE.Color().setHSL( Math.random() * 0.3 + 0.5, 0.75, Math.random() * 0.25 + 0.75 );

        }

        material = new THREE.MeshBasicMaterial( { vertexColors: THREE.VertexColors } );

        mesh = new THREE.Mesh( geometry, material );
        scene.add( mesh );

        // objects

        geometry = new THREE.BoxGeometry( 20, 20, 20 );

        for ( var i = 0, l = geometry.faces.length; i < l; i ++ ) {

          var face = geometry.faces[ i ];
          face.vertexColors[ 0 ] = new THREE.Color().setHSL( Math.random() * 0.3 + 0.5, 0.75, Math.random() * 0.25 + 0.75 );
          face.vertexColors[ 1 ] = new THREE.Color().setHSL( Math.random() * 0.3 + 0.5, 0.75, Math.random() * 0.25 + 0.75 );
          face.vertexColors[ 2 ] = new THREE.Color().setHSL( Math.random() * 0.3 + 0.5, 0.75, Math.random() * 0.25 + 0.75 );

        }

        var link_block_counter = 1;
        <%= for post <- @posts do %>
        // for ( var i = 0; i < 1; i ++ ) {

          material = new THREE.MeshPhongMaterial( { specular: 0xffffff, flatShading: true, vertexColors: THREE.VertexColors } );

          var mesh = new THREE.Mesh( geometry, material );
          mesh.position.x = 0;
          mesh.position.y = 10;
          mesh.position.z = -link_block_counter * 50;

          var heighter = <%= 1 + length(@clicks[post.id] || []) %>;
          mesh.scale.set(1,heighter,1);

          scene.add( mesh );

          material.color.setHSL( Math.random() * 0.2 + 0.5, 0.75, Math.random() * 0.25 + 0.75 );

          objects.push( mesh );

          link_block_counter = link_block_counter + 1;

        // }
        <% end %>
        //

        renderer = new THREE.WebGLRenderer();
        renderer.setPixelRatio( window.devicePixelRatio );
        renderer.setSize( window.innerWidth /2, window.innerHeight /2 );
        var canvas  = document.body.appendChild( renderer.domElement );
        // console.log(canvas);
        canvas.addEventListener( 'click', function ( event ) {

          // instructions.style.display = 'none';

          // Ask the browser to lock the pointer
          element.requestPointerLock = element.requestPointerLock || element.mozRequestPointerLock || element.webkitRequestPointerLock;
          element.requestPointerLock();

        }, false );

        //

        window.addEventListener( 'resize', onWindowResize, false );

      }

      function onWindowResize() {

        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();

        renderer.setSize( window.innerWidth, window.innerHeight );

      }

      function animate() {

        requestAnimationFrame( animate );

        if ( controlsEnabled ) {
          var isOnObject = false;

          var time = performance.now();
          var delta = ( time - prevTime ) / 1000;

          velocity.x -= velocity.x * 10.0 * delta;
          velocity.z -= velocity.z * 10.0 * delta;

          velocity.y -= 9.8 * 0.01 * delta; // 100.0 = mass

          if ( moveForward ) velocity.z -= 400.0 * delta;
          if ( moveBackward ) velocity.z += 400.0 * delta;

          if ( moveLeft ) velocity.x -= 400.0 * delta;
          if ( moveRight ) velocity.x += 400.0 * delta;

          if ( isOnObject === true ) {
            velocity.y = Math.max( 0, velocity.y );

            canJump = true;
          }

          controls.getObject().translateX( velocity.x * delta );
          controls.getObject().translateY( velocity.y * delta );
          controls.getObject().translateZ( velocity.z * delta );

          if ( controls.getObject().position.y < 10 ) {

            velocity.y = 0;
            controls.getObject().position.y = 10;

            canJump = true;

          }

          prevTime = time;

        }

        renderer.render( scene, camera );

      }
</script>

lib/sloth_web/templates/post/new.html.eex
<h2>New Post</h2>

<%= render "form.html", Map.put(assigns, :action, message_path(@conn, :create)) %>

<span><%= link "Back", to: message_path(@conn, :index) %></span>

lib/sloth_web/templates/post/pointerlock.html.eex
<script type="text/javascript">
// https://threejs.org/examples/misc_controls_pointerlock.html
/**
 * @author mrdoob / http://mrdoob.com/
 */

THREE.PointerLockControls = function ( camera ) {

  var scope = this;

  camera.rotation.set( 0, 0, 0 );

  var pitchObject = new THREE.Object3D();
  pitchObject.add( camera );

  var yawObject = new THREE.Object3D();
  yawObject.position.y = 10;
  yawObject.add( pitchObject );

  var PI_2 = Math.PI / 2;

  var onMouseMove = function ( event ) {

    if ( scope.enabled === false ) return;

    var movementX = event.movementX || event.mozMovementX || event.webkitMovementX || 0;
    var movementY = event.movementY || event.mozMovementY || event.webkitMovementY || 0;

    yawObject.rotation.y -= movementX * 0.002;
    pitchObject.rotation.x -= movementY * 0.002;

    pitchObject.rotation.x = Math.max( - PI_2, Math.min( PI_2, pitchObject.rotation.x ) );

  };

  this.dispose = function() {

    document.removeEventListener( 'mousemove', onMouseMove, false );

  };

  document.addEventListener( 'mousemove', onMouseMove, false );

  this.enabled = false;

  this.getObject = function () {

    return yawObject;

  };

  this.getDirection = function() {

    // assumes the camera itself is not rotated

    var direction = new THREE.Vector3( 0, 0, - 1 );
    var rotation = new THREE.Euler( 0, 0, 0, "YXZ" );

    return function( v ) {

      rotation.set( pitchObject.rotation.x, yawObject.rotation.y, 0 );

      v.copy( direction ).applyEuler( rotation );

      return v;

    };

  }();

};
</script>

lib/sloth_web/templates/post/shared_gl.html.eex
<canvas  id="city-canvas"></canvas>


<script id="shader-fs" type="x-shader/x-fragment">
    precision mediump float;        // Set the default precision to medium. We don't need as high of a 
                    // precision in the fragment shader.
    uniform sampler2D u_Texture;    // The input texture.

    varying vec3 v_normal;


    varying vec4 v_Color;           // This is the color from the vertex shader interpolated across the
                      // triangle per fragment.
    varying vec2 v_TexCoordinate;   // Interpolated texture coordinate per fragment.
      
    // The entry point for our fragment shader.
    void main()                       
    {                              
      // because v_normal is a varying it's interpolated
      // we it will not be a uint vector. Normalizing it
      // will make it a unit vector again
      vec3 normal = normalize(v_normal);
 
      vec3 light_source1 = normalize(vec3(1,1,1));
      vec3 light_source2 = normalize(vec3(-1.0,-1.0,1.0));
      vec3 light_source3 = normalize(vec3(1.0, 1.0,-1.0));
      vec3 light_source4 = normalize(vec3(-1.0,1.0,-1.0));

      float light = max(dot(normal, light_source1), 0.0);
      float light1 = max(dot(normal, light_source2), 0.0);
      float light2 = max(dot(normal, light_source3), 0.0);
      float light3 = max(dot(normal, light_source4), 0.0);
      float final_light1 = max(light,light1);
      float final_light2 = max(light2,final_light1);
      float final_light3 = max(light3,final_light2);

      // Multiply the color by the diffuse illumination level and texture value to get final output color.

      vec4 color0 = texture2D(u_Texture, v_TexCoordinate);
      vec4 color1 = v_Color;
      gl_FragColor = color0 * color1;
      // gl_FragColor = v_Color;

      // Lets multiply just the color portion (not the alpha)
      // by the light
      gl_FragColor.rgb *= (0.3 + (final_light3 * 0.7));
      // gl_FragColor.rgb *= final_light3;
    }

</script>


























































<script id="shader-vs" type="x-shader/x-vertex">
    uniform mat4 u_MVPMatrix;   // A constant representing the combined model/view/projection matrix.                

    uniform float u_time;

    attribute vec4 a_Position;    // Per-vertex position information we will pass in.           
    attribute vec4 a_Color;     // Per-vertex color information we will pass in.        
    attribute vec2 a_TexCoordinate; // Per-vertex texture coordinate information we will pass in.
      
    attribute vec3 a_normal;
    
    varying vec3 v_normal;

    varying vec4 v_Color;     // This will be passed into the fragment shader.
    varying vec2 v_TexCoordinate;   // This will be passed into the fragment shader.
      
    // The entry point for our vertex shader.  
    void main()                                                   
    {                                                         
      // Pass through the color.
      v_Color = a_Color;

      v_normal = a_normal;
      
      // Pass through the texture coordinate.
      v_TexCoordinate = a_TexCoordinate;                                      

      // gl_Position is a special variable used to store the final position.
      // Multiply the vertex by the matrix to get the final point in normalized screen coordinates.
      vec4 v = (u_MVPMatrix * a_Position);

      gl_Position =  v; 
      // u_MVPMatrix *                            
    }        
</script>















































<script type="text/javascript">

var gl;
var shaderProgram;
var shaderProgramTree;

var canvas;

var globalStartTex;
var theScene;

//try to move these into daydream controller class
var frameData;
var vrDisplay;
var vrViewFlip = 0;
var globalDaydreamTask = null;

var global_draw_count = 0;



function initGL(canvas) {
    try {
        gl = canvas.getContext('webgl', { premultipliedAlpha: false, alpha: false });
        gl.viewportWidth = canvas.width;
        gl.viewportHeight = canvas.height;

        //allows z testing for overwriting
        gl.enable( gl.DEPTH_TEST );
        gl.depthFunc( gl.LEQUAL );
        gl.depthMask( true );
        gl.disable(gl.BLEND);
        //setting blending and alpha so that images can be transparent when alpha not 1
        // gl.enable(gl.BLEND);
        // gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);

        gl.clearColor(1.0, 1.0, 1.0, 1.0);
        gl.enable(gl.DEPTH_TEST);

        gl.viewport(0, 0, gl.viewportWidth, gl.viewportHeight);
        // gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);

        //culling
        // gl.enable(gl.CULL_FACE);
        // gl.cullFace(gl.BACK);

        // gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, false);s
    } catch (e) {
    }
    if (!gl) {
        alert("Could not initialise WebGL, sorry :-(");
    }
}


function getShader(gl, id) {
    var shaderScript = document.getElementById(id);
    if (!shaderScript) {
        return null;
    }
    var str = "";
    var k = shaderScript.firstChild;
    while (k) {
        if (k.nodeType == 3) {
            str += k.textContent;
        }
        k = k.nextSibling;
    }
    var shader;
    if (shaderScript.type == "x-shader/x-fragment") {
        shader = gl.createShader(gl.FRAGMENT_SHADER);
    } else if (shaderScript.type == "x-shader/x-vertex") {
        shader = gl.createShader(gl.VERTEX_SHADER);
    } else {
        return null;
    }
    gl.shaderSource(shader, str);
    gl.compileShader(shader);
    if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
        alert(gl.getShaderInfoLog(shader));
        return null;
    }
    return shader;
}

function initShaders() {

    var fragmentShader = getShader(gl, "shader-fs");
    var vertexShader = getShader(gl, "shader-vs");
    shaderProgram = gl.createProgram();
    gl.attachShader(shaderProgram, vertexShader);
    gl.attachShader(shaderProgram, fragmentShader);
    gl.linkProgram(shaderProgram);
    if (!gl.getProgramParameter(shaderProgram, gl.LINK_STATUS)) {
        alert("Could not initialise shaders");
    }
    gl.useProgram(shaderProgram);


    shaderProgram.mMVPMatrixHandle = gl.getUniformLocation(shaderProgram, "u_MVPMatrix");
    shaderProgram.mTime = gl.getUniformLocation(shaderProgram, "u_time");
    shaderProgram.mPositionHandle = gl.getAttribLocation(shaderProgram, "a_Position");
    shaderProgram.mColorHandle = gl.getAttribLocation(shaderProgram, "a_Color");
    shaderProgram.mTexHandle = gl.getAttribLocation(shaderProgram, "a_TexCoordinate");
    shaderProgram.mTextureUniformHandle = gl.getUniformLocation(shaderProgram, "u_Texture");

    shaderProgram.mNormalHandle = gl.getAttribLocation(shaderProgram, "a_normal");
   
    // Set the active texture unit to texture //unit 0.
    gl.activeTexture(gl.TEXTURE0);

    // Bind the texture to thi//s unit.
//        GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, mTextureDataHandle);
    //enables repeating texture, uses artificially large map
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.REPEAT);

    // Tell the texture uniform sampler to use this texture in the shader by binding to texture unit 0.
    gl.uniform1i(shaderProgram.mTextureUniformHandle, 0);

}

function webGLStart() {
    canvas = document.getElementById("city-canvas");
    initGL(canvas);
    initShaders();

    //loading a base texture to be used for shapes
    // let newTexture = TextureHelper.loadTextureFromData(loadStartTexture, 'iVBORw0KGgoAAAANSUhEUgAAAQAAAAEABAMAAACuXLVVAAAAA1BMVEUzNDVs\nzlHHAAAAAXRSTlMAQObYZgAAAAlwSFlzAAAAAAAAAAAB6mUWpAAAADZJREFU\neJztwQEBAAAAgiD/r25IQAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nAAAA7waBAAABw08RwAAAAABJRU5ErkJggg==\n');

    // function loadStartTexture(theTexture) {
    //     globalStartTex = Textures.addTexture(theTexture);
    //     setUpScene();
    // }
}





</script>